services:
  #
  # Access
  #
  homepage:
    container_name: homepage
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    labels:
      - "nautical.enable=false"

  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:latest
    restart: unless-stopped
    environment:
      - TS_DEBUG_FIREWALL_MODE=nftables
      - TS_ROUTES=192.168.1.0/24
      - TS_USERSPACE=false
    volumes:
      - /docker/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - net_admin
      - net_raw
    env_file:
      - .env # TS_AUTHKEY
    labels:
      - "nautical.enable=false"

  #
  # Backup
  #
  nautical:
    container_name: nautical
    image: minituff/nautical-backup:latest
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - CRON_SCHEDULE=0 3 * * 6
      - USE_DEST_DATE_FOLDER=true
      - NUMBER_OF_BACKUPS_TO_KEEP=50
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/nautical:/config
      - /docker:/app/source
      - /mnt/disk1/backups:/app/destination
    labels:
      - "nautical.enable=false"

  #
  # Movie/Show Stack
  #
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /docker/jellyfin/config:/config
      - /docker/jellyfin/cache:/cache
      - /mnt/disk2/data/media:/media:ro
    user: 1000:1000

  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /docker/radarr:/config
      - /mnt/disk2/data:/data

  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
    volumes:
      - /docker/sonarr:/config
      - /mnt/disk2/data:/data

  #
  # Other Media
  #
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    ports:
      - 13378:80
    environment:
      - TZ=America/Chicago
    volumes:
      - /docker/audiobookshelf/config:/config
      - /docker/audiobookshelf/metadata:/metadata
      - /mnt/disk2/data/audiobooks:/audiobooks
      - /mnt/disk2/data/podcasts:/podcasts
    user: 1000:1000

  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    ports:
      - 4533:4533
    volumes:
      - /docker/navidrome:/data
      - /mnt/disk2/data/music:/music:ro

  #
  # RSS
  #
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:latest
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - POLLING_FREQUENCY=30
      - POLLING_LIMIT_PER_HOST=1
      - SCHEDULER_ROUND_ROBIN_MIN_INTERVAL=7200 # 5 days
      - SCHEDULER_ROUND_ROBIN_MAX_INTERVAL=7200 # 5 days
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=adminadmin1
    depends_on:
      miniflux-db:
        condition: service_healthy
    labels:
      - "nautical.enable=false"

  miniflux-db:
    container_name: miniflux-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - /docker/miniflux-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

  #
  # Syncing
  # 
  anki-sync-server:
    container_name: anki-sync-server
    image: chrislongros/anki-sync-server-enhanced:latest
    restart: unless-stopped
    ports:
      - 8082:8080 # Sync server
      - 8083:8081 # Dashboard
    environment:
      - TZ=America/Chicago
      - SYNC_USER1=tcardinal:anki
      - DASHBOARD_ENABLED=true
    volumes:
      - /docker/anki-sync-server:/data

  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    restart: unless-stopped
    volumes:
      - /docker/syncthing:/var/syncthing
    network_mode: host

  #
  # Usenet
  #
  sabnzbd:
    container_name: sabnzbd
    image: ghcr.io/hotio/sabnzbd:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Chicago
      - WEBUI_PORTS=8080/tcp,8080/udp
      - ARGS
    volumes:
      - /docker/sabnzbd:/config
      - /mnt/disk2/data/usenet:/data/usenet
