- name: Copy Docker Compose File
  ansible.builtin.copy:
    src: "{{ role_path }}/files/docker-compose.yml"
    dest: "~/docker/{{ role_name }}"

- name: Create and Start Services
  become: yes
  community.docker.docker_compose_v2:
    # TODO: change this from being hardcoded
    project_src: "/home/tcardinal/docker/{{ role_name }}"
    pull: always
  register: output

- name: Show Results
  ansible.builtin.debug:
    var: output
