- name: Install Software
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - build-essential
      - distrobox
      - fish
      - fzf
      - git

- name: Symlink Dotfiles
  ansible.builtin.file: 
    src: "{{ dotfiles_dir }}/{{ item | basename }}"
    dest: "~/{{ item | basename }}"
    state: link
    force: yes
  with_fileglob: "{{ dotfiles_dir }}/.*"

- name: Ensure ~/.config Exists
  ansible.builtin.file:
    path: "~/.config"
    state: directory

- name: Symlink Neovim Directory
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.config/nvim"
    dest: "~/.config/nvim"
    state: link
    force: yes

- name: Symlink Fish Directory
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.config/fish"
    dest: "~/.config/fish"
    state: link
    force: yes

- name: Add Fish to .bashrc
  ansible.builtin.lineinfile:
    path: "~/.bashrc"
    state: present
    line: "exec fish"
